words = [
    "Хроника",
    "Зал",
    "Галера",
    "Балл",
    "Вес",
    "Кафель",
    "Знак",
    "Фильтр",
    "Башня",
    "Кондитер",
    "Омар",
    "Чан",
    "Пламя",
    "Банк",
    "Тетерев",
    "Муж",
    "Камбала",
    "Груз",
    "Кино",
    "Лаваш",
    "Калач",
    "Геолог",
    "Бальзам",
    "Бревно",
    "Борец",
    "Самовар",
    "Карабин",
    "Подлокотник",
    "Барак",
    "Мотор",
    "Сустав",
    "Амфитеатр",
    "Скворечник",
    "Подлодка",
    "Затычка",
    "Ресница",
    "Спичка",
    "Кабан",
    "Муфта",
    "Синоптик",
    "Характер",
    "Мафиози",
    "Фундамент",
    "Бумажник",
    "Дрожжи",
    "Развлечение",
    "Конечность",
    "Пробор",
    "Комбинация",
    "Процессор",
    "Крышка",
    "Сфинкс",
    "Пассатижи",
    "Кружево",
    "Агитатор",
    "Формуляр",
    "Прокол",
    "Абзац",
    "Караван",
    "Леденец",
    "Вращение",
    "Клавиатура",
    "Сегмент",
    "Обещание",
    "Магнитофон",
    "Заварушка"
]
